name: CI

on: 
  pull_request:
    branches:
      - develop
    types: [opened, assigned, synchronize, labeled]


jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 16 ,14]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Run lint
        run: |
          npm run lint
      - name: Run format
        run: |
          npm run format

  lint-staged:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 16 ,14]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Run lint-staged
        run: |
          npm run lint-staged
  
  dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 16, 14]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: npm install    
      - name: Run Dev
        run: |
          npm run dev

   
